spring:
  application:
    name: SGMarket-Backend
  profiles:
    group:
      local: "local, datasource, fcm, pay"
      dev: "dev, datasource, fcm, pay"
      test: "test, fcm, pay"

    include:
      - security
      - coolsms
      - redis
      - imp
      - oauth

swagger:
  version: ${SWAGGER_VERSION:0.0.1}
  url: ${SWAGGER_URL:http://localhost:8080}
