cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      statics: ${AWS_REGION}
    s3:
      bucket-name: ${S3_BUCKET_NAME}
      base-url: ${S3_BASE_URL}