oauth:
  state:
    length: ${OAUTH_STATE_LENGTH:20}
    ttl: ${OAUTH_STATE_TTL:300}
  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID}
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
    redirect-uri: ${OAUTH_NAVER_REDIRECT_URI}