spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  payment:
    secret-key: test-secret-key
    base-url: https://api.test-payments.com/v1/payments

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  access-token-secret: test-access-token-secret-key-for-testing
  access-token-expiration-time: 3600000
  refresh-token-secret: test-refresh-token-secret-key-for-testing
  refresh-token-expiration-time: 604800000
  temporary-token-secret: test-temporary-token-secret-key-for-testing
  temporary-token-expiration-time: 300000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
