jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  temporary-token-secret: ${JWT_TEMPORARY_TOKEN_SECRET}
  temporary-token-expiration-time: ${JWT_TEMPORARY_TOKEN_EXPIRATION_TIME}

